
version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  kibana:
    image: kibana:7.17.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk

  logstash:
    image: logstash:7.17.1
    container_name: logstash
    command: logstash -e 'input { beats { port => 5044 } } output { elasticsearch { hosts => ["elasticsearch:9200"] } } filter { grok { match => { "message" => "%{GREEDYDATA}" } } }'
    ports:
      - 5044:5044
    networks:
      - elk

  filebeat:
    image: elastic/filebeat:8.6.2
    container_name: filebeat
    user: root
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - elk

volumes:
  esdata1:
    driver: local

networks:
  elk:
    driver: bridge
